### ISSUE TITLE
Add support for S3 Analytics 

### ISSUE THREAD

**Issue by mikegrima** [Netflix-Skunkworks/cloudaux#10]
Amazon recently announced new S3 features around analytics.  There are additional API calls that are required:
```
- list_bucket_analytics_configurations()
- list_bucket_inventory_configurations()
- list_bucket_metrics_configurations()
```

This will also require boto's minimum version to be bumped up to `1.4.2`.

**Comment by mikegrima** [comment]
Ready to merge.

**Comment by monkeysecurity** [comment]
Looks like the PR was merged. Closing the issue.
