### ISSUE TITLE
'KeyError' when S3 bucket doesn't contain 'Prefix'

### ISSUE THREAD

**Issue by cstewart87** [Netflix-Skunkworks/cloudaux#17]
Ran into an issue in security monkey when running the S3 watcher:

```
cloudaux/orchestration/aws/s3.py', line 69, in get_lifecycle 'prefix': rule['Prefix'], KeyError: 'Prefix' "
```

Any chance you can update https://github.com/Netflix-Skunkworks/cloudaux/blob/master/cloudaux/orchestration/aws/s3.py#L69 to handle when no prefix exists?

**Comment by mikegrima** [comment]
Fixed in #18
