### ISSUE TITLE
s3 orchestration new fields

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix-Skunkworks/cloudaux#5]
The S3 orchestration should include a field for:
- Region
- Replication?
- Events?

@mikegrima - Anything else?

**Comment by monkeysecurity** [comment]
Region done.

**Comment by mikegrima** [comment]
Working on this now

**Comment by mikegrima** [comment]
The full list should be:
- Website configuration
- Acceleration Configuration
- Bucket ownership information
- Bucket ACLs
- Bucket Policies
- Bucket Creation Date
- Replication Configuration
- Logging
- Tags
- Region
- CORS Rules
- Events
- Tags
- Notifications
- Versioning

**Comment by mikegrima** [comment]
```
load(*args, **kwargs)
Calls s3.Client.list_buckets() to update the attributes of the Bucket resource.
```

SERIOUSLY?!!?!1

**Comment by mikegrima** [comment]
Submitted a WIP PR #6 .

Owners now captured.

**Comment by monkeysecurity** [comment]
:) `Load` sounds like it's exactly what you want, until you find out it's only calling `list_buckets`.

And the `client.list_buckets` only returns the bucket name and creation date iirc.

Is that what the "SERIOUSLY" is for?

**Comment by mikegrima** [comment]
^^ Yes. Listing all buckets in an account just to fetch details from one bucket is less than optimal.

**Comment by mikegrima** [comment]
Will update the `readme` next.

**Comment by mikegrima** [comment]
`README` is updated.

**Comment by mikegrima** [comment]
#6 is done!
