### ISSUE TITLE
optional fields param in orchestration

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix-Skunkworks/cloudaux#7]
I wonder if all the orchestration commands (`get_user`, `get_role`, `get_bucket`) should take an optional fields parameter.

That way you could use CloudAux and specify some subset of the fields.  The default would be all.

Each tech could provide an importable field list so that IDE's could auto-complete.

@mikegrima - Thoughts?

**Comment by mikegrima** [comment]
That works.

**Comment by mikegrima** [comment]
An example is in the S3 orchestration for creation date, since that is an expensive operation (requires a `list_buckets` call to obtain under the hood).

**Comment by monkeysecurity** [comment]
Should the fields be more like `re.DOTALL` and `re.MULTILINE`?

Users could then call something like this:

```
get_bucket('MyBucket', flags=s3.ARN|s3.GRANTS|s3.POLICY)
```

Here's how the python `re` lib implements these:
https://github.com/python/cpython/blob/master/Lib/sre_constants.py#L164

**Comment by monkeysecurity** [comment]
Support added in #30
