### ISSUE TITLE
sts assume role fails 

### ISSUE THREAD

**Issue by PritamDutt** [Netflix-Skunkworks/cloudaux#93]
sts assume role fails with following error in GovCloud at 
https://github.com/Netflix-Skunkworks/cloudaux/blob/ace3daf4ce4205a275fe3f7fa119fc4affc6f5c2/cloudaux/aws/sts.py#L118

`ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied`

Can we somehow pass / implement  ARN_PARTITION / ARN_PREFIX in the likes of what has been done in security_monkey 

https://github.com/Netflix/security_monkey/blob/b174a705124f12aeee612f9ef93820f2b4227e0e/security_monkey/__init__.py#L72

**Comment by mikegrima** [comment]
Probably the best approach would be to make it a keyword argument to: https://github.com/Netflix-Skunkworks/cloudaux/blob/ace3daf4ce4205a275fe3f7fa119fc4affc6f5c2/cloudaux/aws/sts.py#L64-L66

The default value should be the standard `arn:aws:iam:...`, with the option of you being able to send in your own for govcloud.

Please feel free to submit a PR for it.

**Comment by vivaneerApps** [comment]
@mikegrima Thanks I will work on it..

**Comment by PritamDutt** [comment]
@mikegrima Thanks I will work on it..

**Comment by PritamDutt** [comment]
@mikegrima I have raised PR for addressing the requirement. Please have a look at it,

Thanks,
